build[mqbnet]: Fix C++03-incompatible conversion
This patch fixes a conversion from `bslma::ManagedPtr` to
`bsl::shared_ptr` that fails in C++03 with a strict compiler like GCC.

This is the relevant failure, truncated down a lot:

```
/home/runner/work/blazingmq/blazingmq/src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.cpp: In member function ‘BloombergLP::bslma::ManagedPtr<BloombergLP::bmqst::StatContext> BloombergLP::mqbnet::TCPSessionFactory::PortManager::addChannelContext(BloombergLP::bmqst::StatContext*, const bsl::string&, uint16_t)’:
Error: /home/runner/work/blazingmq/blazingmq/src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.cpp:1722:62: error: no matching function for call to ‘BloombergLP::bslma::ManagedPtr<BloombergLP::bmqst::StatContext>::ManagedPtr(BloombergLP::bslma::ManagedPtr<BloombergLP::bmqst::StatContext>)’
 1722 |                 portConfig.storeExpiredSubcontextValues(true));
      |                                                              ^
...
/opt/bb/include/bslma_managedptr_cpp03.h:1837:1: note:   conversion of argument 1 would be ill-formed:
Error: /home/runner/work/blazingmq/blazingmq/src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.cpp:1721:34: error: cannot bind non-const lvalue reference of type ‘BloombergLP::bslma::ManagedPtr<BloombergLP::bmqst::StatContext>&’ to an rvalue of type ‘BloombergLP::bslma::ManagedPtr<BloombergLP::bmqst::StatContext>’
 1721 |             parent->addSubcontext(
      |             ~~~~~~~~~~~~~~~~~~~~~^
 1722 |                 portConfig.storeExpiredSubcontextValues(true));
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Before this patch, we return an rvalue
`bslma::ManagedPtr<bmqst::StatContext>` from `addSubcontext` and then
try to use that to construct a `bsl::shared_ptr<bmqst::StatContext>`
using this constructor:

```cpp
    template <class CONVERTIBLE_TYPE
              BSLSTL_SHAREDPTR_DECLARE_IF_CONVERTIBLE>
    shared_ptr(
         BloombergLP::bslma::ManagedPtr<CONVERTIBLE_TYPE>  managedPtr,
         BloombergLP::bslma::Allocator                    *basicAllocator = 0);
                                                                    // IMPLICIT
```

Calling this constructor needs to invoke
`bslma::ManagedPtr<bmqst::StatContext>`'s copy constructor (which
doesn't exist).  The compiler tries instead to use the constructor
that takes a non-`const` `bslma::ManagedPtr&`, but we can't convert an
rvalue to a non-`const` lvalue ref.

Interestingly, we do construct a `shared_ptr` later from the same
`ManagedPtr` after this patch, but crucially we’re constructing the
`shared_ptr` out of an lvalue `ManagedPtr`, to which we can take a
non-`const` `ManagedPtr&`.

With move semantics in C++11 this works just fine of course, but in
C++03 this is illegal.

Signed-off-by: Patrick M. Niedzielski <pniedzielski@bloomberg.net>